import time
from selenium import webdriver
from selenium.webdriver.support.ui import Select
driver = webdriver.Chrome('chromedriver.exe')
driver.get('http://automationpractice.com/index.php?controller=authentication')
time.sleep(5)
user_box = driver.find_element_by_id('email')
pass_box = driver.find_element_by_id('passwd')
sing_button = driver.find_element_by_id('SubmitLogin')
user_box.send_keys('pruebastr001@gmail.com')
pass_box.send_keys('pruebas1234')
sing_button.click()
address_button = driver.find_element_by_xpath('/html/body/div/div[2]/div/div[3]/div/div/div[1]/ul/li[3]/a')
address_button.click()
time.sleep(5)
new_address_button = driver.find_element_by_xpath('//*[@id="center_column"]/div[2]/a')
new_address_button.click()
address_box = driver.find_element_by_id('address1')
city_box = driver.find_element_by_id('city')
state_Dropdawn = Select(driver.find_element_by_name('id_state'))
zipcode_box = driver.find_element_by_id('postcode')
phone_box = driver.find_element_by_id('phone')
title_address_box = driver.find_element_by_id('alias')
save_button =driver.find_element_by_css_selector('#submitAddress')
address_box.send_keys('Cra 123 # 45')
city_box.send_keys('prueba')
state_Dropdawn.select_by_value("3")
zipcode_box.send_keys('00010')
phone_box.send_keys('3333333')
title_address_box.send_keys('dir_prueba1')
save_button.click()
time.sleep(5)
driver.quit()